(DOCSP-28258): RN fix broken tests (#2678)
## Pull Request Info

RN fix broken tests. broad changes to the RN unit testing suite. 

currently 101/103 tests passing. for 2 remaining failures:

- 1 appears to be SDK bug that is reported in
https://github.com/realm/realm-js/issues/5627
- 1 passes when test run individually but fails when run in suite. will
perform further debugging.

will fix these as part of https://jira.mongodb.org/browse/DOCSP-28787

<details>

<summary>annotated details of test run</summary>

```txt
Summary of all failing tests

~~~~~ this is the seeming SDK bug ~~~~~
 FAIL  __tests__/ts/realm-database/configure-realm-sync-timeout.test.tsx
  ● Instantiate AppWrapperTimeoutSync and test sync

    TypeError: Cannot read properties of undefined (reading 'OpenLocalRealm')

      34 |   const realmAccessBehavior: Realm.OpenRealmBehaviorConfiguration = {
      35 |     type: Realm.OpenRealmBehaviorType.DownloadBeforeOpen,
    > 36 |     timeOutBehavior: Realm.OpenRealmTimeOutBehavior.OpenLocalRealm,
         |                                                     ^
      37 |     timeOut: 1000,
      38 |   };
      39 |

      at OpenLocalRealm (__tests__/ts/realm-database/configure-realm-sync-timeout.test.tsx:36:53)
      at renderWithHooks (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6256:18)
      at mountIndeterminateComponent (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:10702:13)
      at beginWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12151:16)
      at performUnitOfWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:15801:12)
      at workLoopSync (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:15735:5)
      at renderRootSync (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:15707:7)
      at performSyncWorkOnRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:15412:20)
      at flushSyncCallbacks (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2594:22)
      at flushActQueue (node_modules/react/cjs/react.development.js:2665:24)

~~~~~ this is the mysterious bug that works when test run individually ~~~~~
 FAIL  __tests__/ts/sync/multiplex-sync.test.tsx
  ● Multiplex sync

    expect(received).toBe(expected) // Object.is equality

    Expected: true
    Received: false

      54 | test('Multiplex sync', async () => {
      55 |   render(<AppWrapper />);
    > 56 |   await waitFor(async () => {
         |                ^
      57 |     expect(hasRealmBeenOpened).toBe(true);
      58 |   });
      59 | });

      at Object.<anonymous> (__tests__/ts/sync/multiplex-sync.test.tsx:56:16)
      at asyncGeneratorStep (node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
      at _next (node_modules/@babel/runtime/helpers/asyncToGenerator.js:22:9)
      at node_modules/@babel/runtime/helpers/asyncToGenerator.js:27:7
      at tryCallTwo (node_modules/promise/lib/core.js:45:5)
      at doResolve (node_modules/promise/lib/core.js:200:13)
      at new Promise (node_modules/promise/lib/core.js:66:3)
      at Object.<anonymous> (node_modules/@babel/runtime/helpers/asyncToGenerator.js:19:12)


Test Suites: 2 failed, 1 skipped, 57 passed, 59 of 60 total
Tests:       2 failed, 1 skipped, 101 passed, 104 total
```

</details>

### Jira

- https://jira.mongodb.org/browse/DOCSP-28258

### Staged Changes

- [RN SDK (changes to code examples throughout section..don't think need
to look
at)](https://docs-mongodbcom-staging.corp.mongodb.com/realm/docsworker-xlarge/DOCSP-28258/sdk/react-native/)

### Reminder Checklist

If your PR modifies the docs, you might need to also update some
corresponding
pages. Check if completed or N/A.

- [x] Create Jira ticket for corresponding docs-app-services update(s),
if any
- [x] Checked/updated Admin API
- [x] Checked/updated CLI reference

### Review Guidelines


[REVIEWING.md](https://github.com/mongodb/docs-realm/blob/master/REVIEWING.md)